Repository googleinterns/filesystem-in-appsscript, pull requests merged in 2020-07, with the labels that each got.

#64 [Quick Merge] Remove commented Code
  FileSystem/Setup.js
Labels: Quick Merge, Review Ready

#70 [Quick Merge] Change drive error message
  FileSystem/DirectoryManager.js
Labels: Quick Merge, Review Ready

#68 [Quick Merge - Blocker] FileMapper Mocker Update
  FileSystem/FileMapperMocker.js
  FileSystem/FileMapperMockerUtil.js
  FileSystem/FileMapperTests.js
  FileSystem/TestSetup.js
Labels: Blocker PR, Quick Merge, Review Ready

#72 [Easy Merge] Add Mapping to File Mapper
  FileSystem/FileMapperMocker.js
  FileSystem/FileMapperTests.js
  FileSystem/TestSetup.js
  FileSystem/Workbook.js
  FileSystem/appsscript.json
Labels: Quick Merge, Review Ready

#21 [Review - 3] Directory Manager Documentation
  docs/DirectoryManager.md
Labels: Review Ready, documentation

#32 [Review - 2] Directory Manager - All APIs
  FileSystem/DirectoryManager.js
  FileSystem/DirectoryManagerTests.js
  FileSystem/FileIOTests.js
  FileSystem/FileMapperMocker.js
  FileSystem/Util.js
Labels: Review Ready

#40 File Mapper Documentation Updated
  docs/FileMapper.md
Labels: documentation

#76 Blocker method for File Mapper APIs
  FileMapper/blocker_function_setup.js
Labels: Quick Merge

#77 Client-side File Picker library
  FileMapper/environment_variables.html
  FileMapper/picker_library.html
Labels: Quick Merge

#90 [Quick Merge] Fix #43 Rename Util -> Helper
  FileSystem/file_io.js
  FileSystem/file_io_util.js
Labels: Quick Merge, Review Ready

#89 [Quick Merge] Remove Todo
  FileSystem/file_mapper_mocker.js
  FileSystem/test_setup.js
  FileSystem/vba_file_system_classes.js
Labels: Quick Merge, Review Ready

#88 File Mapper APIs Documentation
  docs/FileMapper.md
Labels: Quick Merge, Review Ready

#86 Shared File for getting Mimetype from Extension
  FileMapper/extension_to_mimetype.html
Labels: Review Ready

#74 Updated Local file upload prompt
  FileMapper/fileUploadForm.html
  FileMapper/fileUploadForm_css.html
  FileMapper/fileUploadForm_script.html
  FileMapper/fileuploadform.html
  FileMapper/form.js
Labels: Review Ready

#73 Updated File picker
  FileMapper/picker.js
  FileMapper/pickerPrompt.html
  FileMapper/pickerPrompt_css.html
  FileMapper/pickerPrompt_script.html
  FileMapper/pickerprompt.html
Labels: Review Ready

#47 [Ready - 1] FileSystem: misc
  FileSystem/file_mapper_mocker.js
  FileSystem/file_system.js
  FileSystem/file_system_tests.js
  FileSystem/spreadsheet_logger.js
  FileSystem/test_setup.js
  FileSystem/util.js
Labels: Review Ready

#91 Fixed Filenames
  FileMapper/add_mapping_api.js
  FileMapper/add_mapping_api_tests.js
  FileMapper/api_util.js
  FileMapper/blocker_function_setup.js
  FileMapper/config_script_util.html
  FileMapper/config_setup.js
  FileMapper/config_table.html
  FileMapper/config_util.js
  FileMapper/copy_file_api.js
  FileMapper/copy_file_api_tests.js
  FileMapper/create_file_api.js
  FileMapper/create_file_api_tests.js
  FileMapper/delete_file_api.js
  FileMapper/delete_file_api_tests.js
  FileMapper/environment_variables.html
  FileMapper/file_mapper_work_flow.pdf
  FileMapper/file_picker.js
  FileMapper/file_picker_prompt.html
  FileMapper/file_picker_prompt_css.html
  FileMapper/file_picker_prompt_script.html
  FileMapper/file_upload_form.html
  FileMapper/file_upload_form_css.html
  FileMapper/file_upload_form_script.html
  FileMapper/form.js
  FileMapper/get_drive_id_api.js
  FileMapper/get_drive_id_api_tests.js
  FileMapper/get_pattern_matches_api.js
  FileMapper/get_pattern_matches_api_tests.js
  FileMapper/has_file_api.js
  FileMapper/has_file_api_tests.js
  FileMapper/move_file_api.js
  FileMapper/move_file_api_tests.js
  FileMapper/path_util.js
  FileMapper/qunit_test_setup.js
  FileMapper/show_prompt_choice.js
  FileMapper/show_user_prompt.html
  FileMapper/test_util.js
Labels: Quick Merge, Review Ready

#87 Added Manifest File
  FileMapper/appsscript.json
Labels: Quick Merge, Review Ready

#48 [Ready - 2] FileSystem: Text Stream
  FileSystem/file_io.js
  FileSystem/file_io_util.js
  FileSystem/file_mapper_mocker.js
  FileSystem/file_system.js
  FileSystem/test_setup.js
  FileSystem/vba_file_system_classes.js
  FileSystem/vba_text_stream.js
  FileSystem/vba_text_stream_tests.js
Labels: Review Ready

#49 [Ready - 1] File system - file handling
  FileSystem/api_util.js
  FileSystem/directory_manager.js
  FileSystem/file_mapper_mocker.js
  FileSystem/file_system.js
  FileSystem/file_system_tests.js
  FileSystem/file_system_util.js
  FileSystem/setup.js
  FileSystem/test_setup.js
  FileSystem/util.js
  FileSystem/vba_file_system_classes.js
  FileSystem/vba_structures.js
  docs/DirectoryManager.md
Labels: Review Ready

#95 Flow Chart Updated
  FileMapper/file_mapper_work_flow.pdf
Labels: Quick Merge, Review Ready

#96 Shared Library Setup
  FileMapper/shared_library_setup.js
Labels: Quick Merge, Review Ready
